<div class="page-heading"><div><p class="eyebrow">CHECKOUT</p><h1>Record a sale</h1><p class="subtle">Choose a car, confirm the quantity, and update inventory in one step.</p></div><a class="back-link" href="<?= site_url('sales') ?>">← Sales history</a></div>
<section class="panel form-panel"><form method="post" action="<?= site_url('sales') ?>"><?= csrf_field() ?>
<div class="form-section-head"><span class="form-section-icon">↗</span><div><h2>Transaction details</h2><p>Price is calculated from the car's current listing.</p></div></div>
<div class="field-grid"><div class="field full"><label for="product_id">Car <b>*</b></label><select id="product_id" name="product_id" required><option value="">Select a car</option><?php foreach ($products as $product): ?><option value="<?= $product['id'] ?>" <?= old('product_id') == $product['id'] ? 'selected' : '' ?>><?= esc($product['name']) ?> — $<?= number_format((float) $product['price'], 2) ?> (<?= (int) $product['stock_quantity'] ?> available)</option><?php endforeach; ?></select><?php if (!$products): ?><small>No cars available. <a href="<?= site_url('products/new') ?>">Add one to inventory.</a></small><?php endif; ?></div>
<div class="field"><label for="customer_id">Customer</label><select id="customer_id" name="customer_id"><option value="">Walk-in customer</option><?php foreach ($customers as $customer): ?><option value="<?= $customer['id'] ?>" <?= old('customer_id') == $customer['id'] ? 'selected' : '' ?>><?= esc($customer['full_name']) ?></option><?php endforeach; ?></select></div>
<div class="field"><label for="quantity">Quantity <b>*</b></label><input id="quantity" name="quantity" type="number" min="1" step="1" value="<?= esc(old('quantity', '1')) ?>" required></div></div>
<div class="checkout-note"><span>◈</span><p>Stock is checked when you submit. If availability changed, the sale will be rejected and no inventory will be deducted.</p></div>
<div class="form-footer"><a class="button button-ghost" href="<?= site_url('sales') ?>">Cancel</a><button class="button button-accent" type="submit" <?= !$products ? 'disabled' : '' ?>>Complete sale <span>↗</span></button></div>
</form></section>
